### Working with numerical data
The "data" in *Data Analysis* typically refers to numerical data, e.g., stock prices, sales figures, sensor measurements, sports scores, database tables, etc. The [Numpy](https://numpy.org) library provides specialized data structures, functions, and other tools for numerical computing in Python. Let's work through an example to see why & how to use Numpy for working with numerical data.
> Suppose we want to use climate data like the temperature, rainfall, and humidity to determine if a region is well suited for growing apples. A simple approach for doing this would be to formulate the relationship between the annual yield of apples (tons per hectare) and the climatic conditions like the average temperature (in degrees Fahrenheit), rainfall (in  millimeters) & average relative humidity (in percentage) as a linear equation.
>
> `yield_of_apples = w1 * temperature + w2 * rainfall + w3 * humidity`
We're expressing the yield of apples as a weighted sum of the temperature, rainfall, and humidity. This equation is an approximation since the actual relationship may not necessarily be linear, and there may be other factors involved. But a simple linear model like this often works well in practice.
Based on some statical analysis of historical data, we might come up with reasonable values for the weights `w1`, `w2`, and `w3`. Here's an example set of values:

In [1]:
w1, w2, w3 = 0.3, 0.2, 0.5

Given some climate data for a region, we can now predict the yield of apples. Here's some sample data:
<img src="https://i.imgur.com/TXPBiqv.png" style="width:360px;">
To begin, we can define some variables to record climate data for a region.

In [2]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43


In [3]:
kanto_yield_of_apple = kanto_temp * w1 + kanto_rainfall * w2 + kanto_humidity * w3 
print(kanto_yield_of_apple)


56.8


In [4]:
print("the expected yield of apple is {} ton per hectare in kanto region".format(kanto_yield_of_apple))


the expected yield of apple is 56.8 ton per hectare in kanto region


To make it slightly easier to perform the above computation for multiple regions, we can represent the climate data for each region as a vector, i.e., a list of numbers.

In [5]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]


The three numbers in each vector represent the temperature, rainfall, and humidity data, respectively. 
We can also represent the set of weights used in the formula as a vector.

In [6]:
weights = [w1, w2, w3]


We can now write a function `crop_yield` to calcuate the yield of apples (or any other crop) given the climate data and the respective weights.

In [7]:
def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w 
    return result
    

In [8]:
crop_yield(kanto, weights)

56.8

In [9]:
crop_yield(johto, weights)

76.9

In [10]:
crop_yield(unova, weights)

74.9

## Going from Python lists to Numpy arrays
The calculation performed by the `crop_yield` (element-wise multiplication of two vectors and taking a sum of the results) is also called the *dot product*. Learn more about dot product here: https://www.khanacademy.org/math/linear-algebra/vectors-and-spaces/dot-cross-products/v/vector-dot-product-and-vector-length . 
The Numpy library provides a built-in function to compute the dot product of two vectors. However, we must first convert the lists into Numpy arrays.
Let's install the Numpy library using the `pip` package manager.

In [11]:
! pip install numpy

You should consider upgrading via the '/data/user/0/ru.iiec.pydroid3/files/arm-linux-androideabi/bin/python3.9 -m pip install --upgrade pip' command.


In [12]:
import numpy as np

We can now use the `np.array` function to create Numpy arrays.

In [13]:
kanto = np.array([73, 67, 43])
kanto


array([73, 67, 43])

In [14]:
weights = np.array([w1, w2, w3])
weights


array([0.3, 0.2, 0.5])

Numpy arrays have the type `ndarray`.

In [15]:
type(kanto)

numpy.ndarray

In [16]:
type(weights)

numpy.ndarray

Just like lists, Numpy arrays support the indexing notation `[]`.

In [17]:
kanto[0]


73

In [18]:
weights[1]


0.2

## Operating on Numpy arrays
We can now compute the dot product of the two vectors using the `np.dot` function.

In [19]:
np.dot(kanto, weights)


56.8

We can achieve the same result with low-level operations supported by Numpy arrays: performing an element-wise multiplication and calculating the resulting numbers' sum.

In [20]:
( kanto * weights).sum()

56.8

The `*` operator performs an element-wise multiplication of two arrays if they have the same size. The `sum` method calculates the sum of numbers in an array.

## Benefits of using Numpy arrays
Numpy arrays offer the following benefits over Python lists for operating on numerical data:
- **Ease of use**: You can write small, concise, and intuitive mathematical expressions like `(kanto * weights).sum()` rather than using loops & custom functions like `crop_yield`.
- **Performance**: Numpy operations and functions are implemented internally in C++, which makes them much faster than using Python statements & loops that are interpreted at runtime
Here's a comparison of dot products performed using Python loops vs. Numpy arrays on two vectors with a million elements each.

In [21]:
# Python lists
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

# Numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [22]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1*x2 
result 


CPU times: user 2.31 s, sys: 10 ms, total: 2.32 s
Wall time: 2.33 s


833332333333500000

In [23]:
%%time
np.matmul(arr1_np, arr2_np)


CPU times: user 9.2 ms, sys: 0 ns, total: 9.2 ms
Wall time: 13.7 ms


-1942957984

As you can see, using `np.dot` is 100 times faster than using a `for` loop. This makes Numpy especially useful while working with really large datasets with tens of thousands or millions of data points.

Let's save our work before continuing.

In [24]:
import jovian

## Multi-dimensional Numpy arrays 
We can now go one step further and represent the climate data for all the regions using a single 2-dimensional Numpy array.

In [25]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])
    

In [26]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

If you've taken a linear algebra class in high school, you may recognize the above 2-d array as a matrix with five rows and three columns. Each row represents one region, and the columns represent temperature, rainfall, and humidity, respectively.
Numpy arrays can have any number of dimensions and different lengths along each dimension. We can inspect the length along each dimension using the `.shape` property of an array.
<img src="https://fgnt.github.io/python_crashkurs_doc/_images/numpy_array_t.png" width="420">


In [27]:
# 2D array (matrix)
climate_data.shape

(5, 3)

In [28]:
weights

array([0.3, 0.2, 0.5])

In [29]:
# 1D array (vector)
weights.shape

(3,)

In [30]:
# 3D array 
arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])

In [31]:
arr3.shape

(2, 2, 3)

All the elements in a numpy array have the same data type. You can check the data type of an array using the `.dtype` property.

In [32]:
weights.dtype

dtype('float64')

In [33]:
climate_data.dtype

dtype('int32')

If an array contains even a single floating point number, all the other elements are also converted to floats.

In [34]:
arr3.dtype

dtype('float64')

We can now compute the predicted yields of apples in all the regions, using a single matrix multiplication between `climate_data` (a 5x3 matrix) and `weights` (a vector of length 3). Here's what it looks like visually:
<img src="https://i.imgur.com/LJ2WKSI.png" width="240">
You can learn about matrices and matrix multiplication by watching the first 3-4 videos of this playlist: https://www.youtube.com/watch?v=xyAuNHPsq-g&list=PLFD0EB975BA0CC1E0&index=1 .
We can use the `np.matmul` function or the `@` operator to perform matrix multiplication.

In [35]:
%%time
np.matmul(climate_data, weights)

CPU times: user 242 µs, sys: 54 µs, total: 296 µs
Wall time: 347 µs


array([56.8, 76.9, 81.9, 57.7, 74.9])

In [36]:
%%time
climate_data @ weights

CPU times: user 187 µs, sys: 42 µs, total: 229 µs
Wall time: 317 µs


array([56.8, 76.9, 81.9, 57.7, 74.9])

## Working with CSV data files

Numpy also provides helper functions reading from & writing to files. Let's download a file `climate.txt`, which contains 10,000 climate measurements (temperature, rainfall & humidity) in the following format:


```
temperature,rainfall,humidity
25.00,76.00,99.00
39.00,65.00,70.00
59.00,45.00,77.00
84.00,63.00,38.00
66.00,50.00,52.00
41.00,94.00,77.00
91.00,57.00,96.00
49.00,96.00,99.00
67.00,20.00,28.00
...
```

This format of storing data is known as *comma-separated values* or CSV. 

> **CSVs**: A comma-separated values (CSV) file is a delimited text file that uses a comma to separate values. Each line of the file is a data record. Each record consists of one or more fields, separated by commas. A CSV file typically stores tabular data (numbers and text) in plain text, in which case each line will have the same number of fields. (Wikipedia)


To read this file into a numpy array, we can use the `genfromtxt` function.

In [37]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv',
    'climate.txt')
    

('climate.txt', <http.client.HTTPMessage at 0xab1e5b98>)

In [38]:
climate_data = np.genfromtxt(
    'climate.txt',
    delimiter=',',
    skip_header=1)


In [39]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [40]:
climate_data.shape

(10000, 3)

We can now perform a matrix multiplication using the `@` operator to predict the yield of apples for the entire dataset using a given set of weights.

In [41]:
weights = np.array([0.3, 0.2, 0.5])

In [42]:
yields = climate_data @ weights

In [43]:
yields 

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [44]:
yields.shape

(10000,)

Let's add the `yields` to `climate_data` as a fourth column using the [`np.concatenate`](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) function.

In [45]:
climate_result = np.concatenate(
    (climate_data, yields.reshape(10000,1)),
     axis = 1)
  

In [46]:
climate_result

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

There are a couple of subtleties here:
* Since we wish to add new columns, we pass the argument `axis=1` to `np.concatenate`. The `axis` argument specifies the dimension for concatenation.
*  The arrays should have the same number of dimensions, and the same length along each except the dimension used for concatenation. We use the [`np.reshape`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) function to change the shape of `yields` from `(10000,)` to `(10000,1)`.
Here's a visual explanation of `np.concatenate` along `axis=1` (can you guess what `axis=0` results in?):
<img src="https://www.w3resource.com/w3r_images/python-numpy-image-exercise-58.png" width="300">
The best way to understand what a Numpy function does is to experiment with it and read the documentation to learn about its arguments & return values. Use the cells below to experiment with `np.concatenate` and `np.reshape`.

Let's write the final results from our computation above back to a file using the `np.savetxt` function.

In [47]:
climate_result

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [48]:
np.savetxt('climate_result.txt',
           climate_result,
           fmt='%.2f',
           delimiter=',',
           comments='',
           header='temperature,rainfall,humidity,yield_apples'
           )

The results are written back in the CSV format to the file `climate_results.txt`. 
```
temperature,rainfall,humidity,yeild_apples
25.00,76.00,99.00,72.20
39.00,65.00,70.00,59.70
59.00,45.00,77.00,65.20
84.00,63.00,38.00,56.80
...
```


Numpy provides hundreds of functions for performing operations on arrays. Here are some commonly used functions:
* Mathematics: `np.sum`, `np.exp`, `np.round`, arithemtic operators 
* Array manipulation: `np.reshape`, `np.stack`, `np.concatenate`, `np.split`
* Linear Algebra: `np.matmul`, `np.dot`, `np.transpose`, `np.eigvals`
* Statistics: `np.mean`, `np.median`, `np.std`, `np.max`
> **How to find the function you need?** The easiest way to find the right function for a specific operation or use-case is to do a web search. For instance, searching for "How to join numpy arrays" leads to [this tutorial on array concatenation](https://cmdlinetips.com/2018/04/how-to-concatenate-arrays-in-numpy/). 
You can find a full list of array functions here: https://numpy.org/doc/stable/reference/routines.html

## Arithmetic operations, broadcasting and comparison
Numpy arrays support arithmetic operators like `+`, `-`, `*`, etc. You can perform an arithmetic operation with a single number (also called scalar) or with another array of the same shape. Operators make it easy to write mathematical expressions with multi-dimensional arrays.

### Array Broadcasting
Numpy arrays also support *broadcasting*, allowing arithmetic operations between two arrays with different numbers of dimensions but compatible shapes. Let's look at an example to see how it works.

In [49]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [50]:
arr2.shape

(3, 4)

In [51]:
arr4 = np.array([4, 5, 6, 7])

In [52]:
arr4.shape

(4,)

In [53]:
arr2 + arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

When the expression `arr2 + arr4` is evaluated, `arr4` (which has the shape `(4,)`) is replicated three times to match the shape `(3, 4)` of `arr2`. Numpy performs the replication without actually creating three copies of the smaller dimension array, thus improving performance and using lower memory.
<img src="https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png" width="360">
Broadcasting only works if one of the arrays can be replicated to match the other array's shape.

### Array Comparison
Numpy arrays also support comparison operations like `==`, `!=`, `>` etc. The result is an array of booleans.

Array comparison is frequently used to count the number of equal elements in two arrays using the `sum` method. Remember that `True` evaluates to `1` and `False` evaluates to `0` when booleans are used in arithmetic operations.

In [54]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

In [55]:
(arr1 == arr2).sum()

3

## Array indexing and slicing
Numpy extends Python's list indexing notation using `[]` to multiple dimensions in an intuitive fashion. You can provide a comma-separated list of indices or ranges to select a specific element or a subarray (also called a slice) from a Numpy array.

The notation and its results can seem confusing at first, so take your time to experiment and become comfortable with it. Use the cells below to try out some examples of array indexing and slicing, with different combinations of indices and ranges. Here are some more examples demonstrated visually:
<img src="https://scipy-lectures.org/_images/numpy_indexing.png" width="360">

In [56]:
arr_exp = np.arange(0,36)
arr_exp                  

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [57]:
arr_exp = arr_exp.reshape(6,6)
arr_exp

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [58]:
arr_exp[2:-2,::2]
# OR 
arr_exp[2::2,::2]

array([[12, 14, 16],
       [24, 26, 28]])

In [59]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## CSV files mts 

In [60]:
generated_data = np.random.randint(40,99,30000)
generated_data


array([74, 62, 68, ..., 53, 81, 85])

In [61]:
generated_data=generated_data.reshape(10000,3)
generated_data


array([[74, 62, 68],
       [78, 62, 74],
       [67, 89, 74],
       ...,
       [44, 95, 42],
       [81, 91, 88],
       [53, 81, 85]])

In [62]:
np.savetxt('generated_data.txt',
           generated_data,
           fmt='%.2f',
           delimiter=',',
           header='temperature,rainfall,humidity',
           comments='')
           

the generated data is saved in CSV format to the file `generated_data.txt`.

To read this file into a numpy array, we can use the `genfromtxt` function.

In [63]:
climate_data2 = np.genfromtxt(
    'generated_data.txt',
    delimiter = ',',
    skip_header = 1)


In [64]:
climate_data2

array([[74., 62., 68.],
       [78., 62., 74.],
       [67., 89., 74.],
       ...,
       [44., 95., 42.],
       [81., 91., 88.],
       [53., 81., 85.]])

In [65]:
climate_data2.shape

(10000, 3)

In [66]:
climate_data2.size

30000

In [67]:
yield_apples2 = climate_data2 @ weights 
yield_apples2


array([68.6, 72.8, 74.9, ..., 53.2, 86.5, 74.6])

In [68]:
yield_apples2.shape
# 1000 columns.

(10000,)

In [69]:
yield_apples2.size


10000

Let's add the `yields` to `climate_data2` as a fourth column using the `np.concatenate` function.

In [70]:
climate_result2 = np.concatenate(
    (climate_data2,
    yield_apples2.reshape(10000,1)),
    axis = 1)
# it's reshaped into 1000rows 
# and 1 column for concatenation 
# purpose.
    

In [71]:
climate_result2

array([[74. , 62. , 68. , 68.6],
       [78. , 62. , 74. , 72.8],
       [67. , 89. , 74. , 74.9],
       ...,
       [44. , 95. , 42. , 53.2],
       [81. , 91. , 88. , 86.5],
       [53. , 81. , 85. , 74.6]])

In [72]:
np.savetxt('climate_result2.txt',
           climate_result2,
           fmt='%.2f',
           delimiter=',',
           header='temperature,rainfall,humidity,yield_apples2',
           comments='')
           

the array `climate_result2` is saved in a `CSV format` to the file `climate_result2.txt`.