In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[2.0,
  4.0,6.0]], dtype='float32') 
print(b)

[[9. 8. 7.]
 [2. 4. 6.]]


In [4]:
#get dimension.
a.ndim
b.ndim

2

In [5]:
#get shape 
b.shape

(2, 3)

In [6]:
#get type 
b.dtype

dtype('float32')

In [7]:
#get size 
b.itemsize

4

In [8]:
#get total size 
b.nbytes
a.nbytes

12

# Accessing/Changing specific rows,colums,e.t.c.

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
#accessing an element 
a[1,5]

13

In [11]:
#accessing a row 
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [12]:
#accessing a column 
a[:,3]

array([ 4, 11])

In [13]:
#getting a little more
# fancy[startindex:endindex:step]

a[0,1:6:2]

array([2, 4, 6])

In [14]:
#changing specific elements, rows, elements e.t.c.
a[1,5]=20
#row 2 and all columns hahaha!
a[1,:]=7,6,5,4,3,2,1
print(a)

[[1 2 3 4 5 6 7]
 [7 6 5 4 3 2 1]]


*3-d array

In [15]:
b=np.array([[[1,2],[3,4]],[[5,6],
           [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
#accessing specific elements 
b[0,1,-1]
b[0,0,0]

1

In [17]:
#changing specific elements 
b[:,0,:]=[[2,1],[7,0]]
print(b)

[[[2 1]
  [3 4]]

 [[7 0]
  [7 8]]]


# Initializing different types of Array.

In [18]:
#All 0s matrix 
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [19]:
#all 1s matrix
d = np.ones((4,3,2), dtype='int32')
print(d)


[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


In [20]:
# Any other number
np.full((2,2),99,dtype="int32")

array([[99, 99],
       [99, 99]])

In [21]:
# Any other number (full_like)
np.full_like(b,69)

array([[[69, 69],
        [69, 69]],

       [[69, 69],
        [69, 69]]])

In [22]:
# Random decimal numbers 
np.random.rand(4,4)

array([[0.45831742, 0.96895076, 0.11387015, 0.22850788],
       [0.9017018 , 0.56562841, 0.33031166, 0.56834534],
       [0.0818972 , 0.1201265 , 0.4938086 , 0.51421981],
       [0.44286391, 0.16796106, 0.83334543, 0.67979578]])

In [23]:
#random decimal number[random sample] 
np.random.random_sample(b.shape)

array([[[0.04220933, 0.51026345],
        [0.11289206, 0.08027875]],

       [[0.92750301, 0.16867337],
        [0.43759625, 0.17015202]]])

In [24]:
# random integer number 
basic=np.random.randint(4, size=(3,3,3))
print(basic)
check=np.random.randint(7, size=b.shape)
print(check)


[[[2 3 0]
  [3 1 1]
  [2 1 1]]

 [[1 2 3]
  [0 1 0]
  [0 2 0]]

 [[3 2 0]
  [0 2 0]
  [0 1 2]]]
[[[4 5]
  [3 1]]

 [[1 2]
  [2 3]]]


In [25]:
# Identity matrix 
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
arr = np.array([[1,0,1,1,0]])
r1=np.repeat(arr,5, axis=0)
print(r1)

[[1 0 1 1 0]
 [1 0 1 1 0]
 [1 0 1 1 0]
 [1 0 1 1 0]
 [1 0 1 1 0]]


In [27]:
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4]=z 
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [28]:
a=np.array([1,2,3])
b=a 
b[1]=0
print(b)
print(a)


[1 0 3]
[1 0 3]


☝️❌

In [29]:
a=np.array([1,2,3])
b=a.copy()
b[1]=0
print(b)
print(a)


[1 0 3]
[1 2 3]


☝️✔️

# Mathematics 

In [30]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [31]:
a + 2


array([3, 4, 5, 6])

In [32]:
a - 2

array([-1,  0,  1,  2])

In [33]:
a * 2

array([2, 4, 6, 8])

In [34]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [35]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [36]:
a//2

array([0, 1, 1, 2], dtype=int32)

In [37]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [38]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# Linear Algebra

In [39]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [40]:
 
c = np.random.randint(6,size=(3,3))
print(c)

[[1 0 4]
 [3 4 0]
 [1 2 2]]


In [41]:
# Find the determinant
int(np.linalg.det(c))

15

# Statistics

In [42]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [43]:
np.min(stats, axis=1)

array([1, 4])

In [44]:
np.max(stats, axis=1)

array([3, 6])

# Reorganizing Arrays

In [45]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape(8,1)
print(after)


[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [46]:
#Vertically stacking vectors 
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [47]:
#Horizontally stacking vectors 
h1 = np.ones((3,1))
h2 = np.array([[1],[0],[1]])

np.hstack([h1,h2,h1])

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

# Miscellaneous 

##### Load from file

In [48]:
#loading texts from other files 
filedata = np.genfromtxt("data.txt", delimiter = ",")
filedata =  filedata.astype("int32")
print(filedata)

                

OSError: data.txt not found.

##### Boolean Masking and Advanced Indexing

In [ ]:
filedata > 50

In [ ]:
filedata[filedata > 50]

In [ ]:
np.any(filedata > 50, axis=1)

In [ ]:
np.all(filedata > 50,axis=0)

In [ ]:
((filedata > 50) & (filedata < 100))
 

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

### Let's play

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.array([11,12,13,14,15])
d = np.array([16,17,18,19,20])
e = np.array([21,22,23,24,25])
f = np.array([26,27,28,29,30])

all = np.vstack([a,b,c,d,e,f])
print(all)

square = all[2:4,0:2] #will work 
             #for rectangle also
diagonal = all[[0,1,2,3],[1,2,3,4]]
scattered= all[[0,4,5],3:]

print(square)
print(diagonal)
print(scattered)
